# Diabetes Dataset Assignment | Linear Regression

In [1]:
import pandas as pd
import numpy as np

## Importing the Data

In [3]:
diabetes = np.genfromtxt("diabetes_train_data.csv", dtype = None, delimiter = ",")
print(diabetes)
print(diabetes.shape)

[[-4.91050164e-02 -4.46416365e-02  1.60854917e-01 ...  2.80165065e-02
   1.13486232e-02  3.46000000e+02]
 [-7.09002471e-02  5.06801187e-02 -8.91974838e-02 ... -1.29079423e-02
  -5.49250874e-02  1.04000000e+02]
 [ 1.75052192e-03 -4.46416365e-02 -7.08746786e-02 ... -2.25121719e-02
   7.20651633e-03  4.90000000e+01]
 ...
 [ 2.35457526e-02 -4.46416365e-02  7.03187031e-02 ... -1.91970476e-02
  -9.36191133e-03  2.88000000e+02]
 [ 1.62806757e-02  5.06801187e-02  7.24743273e-02 ... -2.36445576e-02
   6.10539062e-02  1.31000000e+02]
 [-9.14709343e-03  5.06801187e-02 -3.09956318e-02 ...  6.20931562e-03
   2.79170509e-02  4.20000000e+01]]
(331, 11)

## Converting Data to DataFrame

#### I am converting the data to DataFrame as the Output data is also added in the dataset and we need to separate the output data.

In [4]:
diabetes_dataframe = pd.DataFrame(diabetes)
diabetes_dataframe

,0,1,2,3,4,5,6,7,8,9,10
0,-0.049105,-0.044642,0.160855,-0.046985,-0.029088,-0.019790,-0.047082,0.034309,0.028017,0.011349,346.0
1,-0.070900,0.050680,-0.089197,-0.074528,-0.042848,-0.025739,-0.032356,-0.002592,-0.012908,-0.054925,104.0
2,0.001751,-0.044642,-0.070875,-0.022885,-0.001569,-0.001001,0.026550,-0.039493,-0.022512,0.007207,49.0
3,0.048974,0.050680,0.081097,0.021872,0.043837,0.064134,-0.054446,0.071210,0.032433,0.048628,180.0
4,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014956,0.011349,110.0
...,...,...,...,...,...,...,...,...,...,...,...
326,0.012648,-0.044642,-0.020218,-0.015999,0.012191,0.021233,-0.076536,0.108111,0.059881,-0.021788,233.0
327,0.019913,-0.044642,-0.057941,-0.057314,-0.001569,-0.012587,0.074412,-0.039493,-0.061177,-0.075636,63.0
328,0.023546,-0.044642,0.070319,0.025315,-0.034592,-0.014466,-0.032356,-0.002592,-0.019197,-0.009362,288.0
329,0.016281,0.050680,0.072474,0.076958,-0.008449,0.005575,-0.006584,-0.002592,-0.023645,0.061054,131.0
330,-0.009147,0.050680,-0.030996,-0.026328,-0.011201,-0.001001,-0.021311,-0.002592,0.006209,0.027917,42.0

## Separating the Input and Output

In [7]:
diabetes_input = diabetes_dataframe.iloc[:,0:10]
diabetes_output = diabetes_dataframe.iloc[:,10]

In [8]:
diabetes_input

,0,1,2,3,4,5,6,7,8,9
0,-0.049105,-0.044642,0.160855,-0.046985,-0.029088,-0.019790,-0.047082,0.034309,0.028017,0.011349
1,-0.070900,0.050680,-0.089197,-0.074528,-0.042848,-0.025739,-0.032356,-0.002592,-0.012908,-0.054925
2,0.001751,-0.044642,-0.070875,-0.022885,-0.001569,-0.001001,0.026550,-0.039493,-0.022512,0.007207
3,0.048974,0.050680,0.081097,0.021872,0.043837,0.064134,-0.054446,0.071210,0.032433,0.048628
4,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014956,0.011349
...,...,...,...,...,...,...,...,...,...,...
326,0.012648,-0.044642,-0.020218,-0.015999,0.012191,0.021233,-0.076536,0.108111,0.059881,-0.021788
327,0.019913,-0.044642,-0.057941,-0.057314,-0.001569,-0.012587,0.074412,-0.039493,-0.061177,-0.075636
328,0.023546,-0.044642,0.070319,0.025315,-0.034592,-0.014466,-0.032356,-0.002592,-0.019197,-0.009362
329,0.016281,0.050680,0.072474,0.076958,-0.008449,0.005575,-0.006584,-0.002592,-0.023645,0.061054
330,-0.009147,0.050680,-0.030996,-0.026328,-0.011201,-0.001001,-0.021311,-0.002592,0.006209,0.027917

In [9]:
diabetes_output

0      346.0
1      104.0
2       49.0
3      180.0
4      110.0
       ...
326    233.0
327     63.0
328    288.0
329    131.0
330     42.0
Name: 10, Length: 331, dtype: float64

## Converting the Data to Numpy Array

In [10]:
X_train = diabetes_input.to_numpy()
Y_train = diabetes_output.to_numpy()
X_train, Y_train

(array([[-0.04910502, -0.04464164,  0.16085492, ...,  0.03430886,
          0.02801651,  0.01134862],
        [-0.07090025,  0.05068012, -0.08919748, ..., -0.00259226,
         -0.01290794, -0.05492509],
        [ 0.00175052, -0.04464164, -0.07087468, ..., -0.03949338,
         -0.02251217,  0.00720652],
        ...,
        [ 0.02354575, -0.04464164,  0.0703187 , ..., -0.00259226,
         -0.01919705, -0.00936191],
        [ 0.01628068,  0.05068012,  0.07247433, ..., -0.00259226,
         -0.02364456,  0.06105391],
        [-0.00914709,  0.05068012, -0.03099563, ..., -0.00259226,
          0.00620932,  0.02791705]]),
 array([346., 104.,  49., 180., 110.,  72.,  68., 216.,  47., 296.,  65.,
         96.,  67.,  52., 100., 202., 128.,  63., 281., 152., 124., 245.,
        101., 113.,  48., 197., 186., 132., 245.,  91.,  43., 101., 111.,
        199., 220., 281., 217.,  93., 174., 150., 206.,  61.,  55., 118.,
         53., 275., 215., 142.,  90.,  65., 200.,  96., 249., 200., 155.,
        170., 141., 179., 225.,  61., 103., 131., 158., 275., 246.,  97.,
        302.,  91., 178.,  51., 170., 104., 168., 257., 182.,  71., 220.,
        241., 192., 220., 220., 141.,  89., 144., 150., 135., 200.,  39.,
         25., 185.,  52.,  92.,  63., 152.,  69.,  68., 274., 279., 236.,
        168., 143., 135., 123., 277.,  60.,  72.,  72., 109.,  86.,  92.,
         99.,  48., 170., 283., 129.,  75., 270., 272.,  31., 262., 232.,
        191., 140., 233., 196., 263.,  88.,  84., 137., 128.,  78., 140.,
        252.,  55., 104., 235.,  37., 122.,  72., 144., 138., 253.,  90.,
         53., 198., 145.,  73., 252.,  77., 295., 243.,  83., 212., 185.,
        126.,  68., 210., 107., 200.,  69.,  98., 242., 163., 172.,  40.,
        109.,  39., 202., 131., 261.,  71., 200.,  60., 198., 198., 107.,
        252., 144., 108.,  64.,  83.,  67., 146.,  84.,  96., 270.,  80.,
        182., 214., 127., 143., 222.,  50.,  85., 115., 243., 281., 258.,
        114.,  57.,  94., 136.,  88., 178.,  94.,  81.,  42., 102., 139.,
         74.,  69., 308., 200., 242., 158., 174.,  66.,  78., 127., 132.,
        201., 178., 202.,  66., 248., 237., 120., 111.,  99.,  96., 180.,
        341., 219., 131., 141.,  89.,  59., 147.,  44., 336.,  47., 272.,
        317., 161.,  64.,  78., 111., 208., 190., 244., 246.,  48., 275.,
        182., 248.,  59., 178., 113., 109., 142.,  59., 110., 128.,  95.,
         65., 115., 276.,  85., 183.,  58.,  71., 162., 225., 306., 137.,
         85.,  77.,  72., 166., 310.,  79., 195., 321., 160., 283.,  75.,
        167., 191.,  71., 297., 185., 134., 233., 151.,  83., 258.,  54.,
         55., 189.,  70., 310., 181., 172., 235., 275., 259.,  88.,  74.,
         91., 104., 173., 179., 148., 168., 124., 164., 214., 263.,  52.,
         52., 160.,  88.,  94., 109.,  53., 265., 233.,  63., 288., 131.,
         42.]))

## Training the Linear Regression Algorithm

In [11]:
from sklearn.linear_model import LinearRegression
alg = LinearRegression()

## Fit the Data in Algorithm

In [12]:
alg.fit(X_train,Y_train)

LinearRegression()

## Importing the Test Data for Prediction

In [13]:
X_test = np.genfromtxt("diabetes_test_data.csv", dtype = None, delimiter = ',')
X_test

array([[ 0.02354575,  0.05068012, -0.0374625 , ..., -0.03949338,
        -0.03075121, -0.01350402],
       [-0.07816532, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.01811827, -0.08391984],
       [-0.03094232,  0.05068012,  0.00133873, ...,  0.1081111 ,
         0.08379677,  0.00306441],
       ...,
       [ 0.0090156 , -0.04464164, -0.01267283, ...,  0.03430886,
         0.02337484, -0.0052198 ],
       [ 0.01991321, -0.04464164, -0.03422907, ...,  0.03283281,
         0.02472532,  0.06933812],
       [ 0.01628068,  0.05068012,  0.00996123, ..., -0.03949338,
         0.01703713,  0.00720652]])

## Predicting the Output on X_test Data

In [14]:
Y_pred = alg.predict(X_test)
Y_pred

array([105.52974799, 105.8039198 , 178.60857225,  79.3828781 ,
        52.95868706,  98.87263854, 150.71755448,  34.86515216,
       113.13535727, 161.50184038, 135.8615611 ,  94.71592222,
       138.48094422, 141.37441723, 158.76862662, 171.65288616,
       106.44835654, 103.92659639,  95.38693889, 167.40118092,
       166.53426278, 101.53464712, 252.45035972, 147.02258547,
       214.78906632, 161.27557106, 210.61315228,  71.78091585,
       189.65032431, 206.6134259 , 219.98643455, 168.80192534,
       116.84846127, 178.74399639,  77.03247418,  59.54633214,
       111.5673781 , 156.95186739, 154.59591259, 198.94457493,
       115.53884017, 153.46699024,  84.96179518, 113.70337192,
       142.14155617, 147.31040378,  82.78072358,  77.89237327,
       128.99006192, 261.58712282, 213.31187775, 243.98791257,
       167.68132094, 183.69712124, 166.85926884, 202.11440188,
       220.39235543, 172.40288024, 176.60897931, 109.04656567,
       276.37789836,  90.99941821, 289.37221147, 119.56253351,
        75.45687948, 180.78598759, 146.62093081, 156.42382465,
        41.079036  , 247.90645166, 207.99121432,  90.09641075,
       222.24169638, 189.86378006, 182.2695376 , 164.39881376,
       190.27066587, 105.4486795 , 199.86136394, 245.796388  ,
       123.20281334, 119.41031908, 145.86620411, 206.19247291,
       150.86282453, 142.23221646, 154.56874616, 115.29233396,
       134.07810123, 118.42225404, 203.5767555 , 170.66483797,
       127.409797  ,  57.13507634, 231.92226503, 185.20713654,
       187.37494558,  83.55920849, 185.42585685, 217.34035639,
       108.86715354,  80.98714568, 127.05524123, 242.00738792,
       155.9723414 , 125.67575276, 246.41235643, 234.963933  ,
       191.51298252, 168.33254477, 163.02965178])

## Setting Predicted Output to 5 Decimal Places

In [15]:
Y_pred = np.around(Y_pred,5)
Y_pred

array([105.52975, 105.80392, 178.60857,  79.38288,  52.95869,  98.87264,
       150.71755,  34.86515, 113.13536, 161.50184, 135.86156,  94.71592,
       138.48094, 141.37442, 158.76863, 171.65289, 106.44836, 103.9266 ,
        95.38694, 167.40118, 166.53426, 101.53465, 252.45036, 147.02259,
       214.78907, 161.27557, 210.61315,  71.78092, 189.65032, 206.61343,
       219.98643, 168.80193, 116.84846, 178.744  ,  77.03247,  59.54633,
       111.56738, 156.95187, 154.59591, 198.94457, 115.53884, 153.46699,
        84.9618 , 113.70337, 142.14156, 147.3104 ,  82.78072,  77.89237,
       128.99006, 261.58712, 213.31188, 243.98791, 167.68132, 183.69712,
       166.85927, 202.1144 , 220.39236, 172.40288, 176.60898, 109.04657,
       276.3779 ,  90.99942, 289.37221, 119.56253,  75.45688, 180.78599,
       146.62093, 156.42382,  41.07904, 247.90645, 207.99121,  90.09641,
       222.2417 , 189.86378, 182.26954, 164.39881, 190.27067, 105.44868,
       199.86136, 245.79639, 123.20281, 119.41032, 145.8662 , 206.19247,
       150.86282, 142.23222, 154.56875, 115.29233, 134.0781 , 118.42225,
       203.57676, 170.66484, 127.4098 ,  57.13508, 231.92227, 185.20714,
       187.37495,  83.55921, 185.42586, 217.34036, 108.86715,  80.98715,
       127.05524, 242.00739, 155.97234, 125.67575, 246.41236, 234.96393,
       191.51298, 168.33254, 163.02965])

## Saving the Prediction

In [16]:
np.savetxt('C:/Users/hp/Machine Learning Coding Ninjas/Milestone 2/Linear Regression - Diabetes Dataset Assignment/pred.csv', Y_pred)