# Boston Dataset

In [1]:
from sklearn import datasets

## Importing Boston Data

In [2]:
boston = datasets.load_boston()
print(boston)

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]]), 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21.5, 19.6, 15.3, 19.4,
       17. , 15.6, 13.1, 41.3, 24.3, 23.3, 27. , 50. , 50. , 50. , 22.7,
       25. , 50. , 23.8, 23.8, 22.3, 17.4, 19.1, 23.1, 23.6, 22.6, 29.4,
       23.2, 24.6, 29.9, 37.2, 39.8, 36.2, 37.9, 32.5, 26.4, 29.6, 50. ,
       32. , 29.8, 34.9, 37. , 30.5, 36.4, 31.1, 29.1, 50. , 33.3, 30.3,
       34.6, 34.9, 32.9, 24.1, 42.3, 48.5, 50. , 22.6, 24.4, 22.5, 24.4,
       20. , 21.7, 19.3, 22.4, 28.1, 23.7, 25. , 23.3, 28.7, 21.5, 23. ,
       26.7, 21.7, 27.5, 30.1, 44.8, 50. , 37.6, 31.6, 46.7, 31.5, 24.3,
       31.7, 41.7, 48.3, 29. , 24. , 25.1, 31.5, 23.7, 23.3, 22. , 20.1,
       22.2, 23.7, 17.6, 18.5, 24.3, 20.5, 24.5, 26.2, 24.4, 24.8, 29.6,
       42.8, 21.9, 20.9, 44. , 50. , 36. , 30.1, 33.8, 43.1, 48.8, 31. ,
       36.5, 22.8, 30.7, 50. , 43.5, 20.7, 21.1, 25.2, 24.4, 35.2, 32.4,
       32. , 33.2, 33.1, 29.1, 35.1, 45.4, 35.4, 46. , 50. , 32.2, 22. ,
       20.1, 23.2, 22.3, 24.8, 28.5, 37.3, 27.9, 23.9, 21.7, 28.6, 27.1,
       20.3, 22.5, 29. , 24.8, 22. , 26.4, 33.1, 36.1, 28.4, 33.4, 28.2,
       22.8, 20.3, 16.1, 22.1, 19.4, 21.6, 23.8, 16.2, 17.8, 19.8, 23.1,
       21. , 23.8, 23.1, 20.4, 18.5, 25. , 24.6, 23. , 22.2, 19.3, 22.6,
       19.8, 17.1, 19.4, 22.2, 20.7, 21.1, 19.5, 18.5, 20.6, 19. , 18.7,
       32.7, 16.5, 23.9, 31.2, 17.5, 17.2, 23.1, 24.5, 26.6, 22.9, 24.1,
       18.6, 30.1, 18.2, 20.6, 17.8, 21.7, 22.7, 22.6, 25. , 19.9, 20.8,
       16.8, 21.9, 27.5, 21.9, 23.1, 50. , 50. , 50. , 50. , 50. , 13.8,
       13.8, 15. , 13.9, 13.3, 13.1, 10.2, 10.4, 10.9, 11.3, 12.3,  8.8,
        7.2, 10.5,  7.4, 10.2, 11.5, 15.1, 23.2,  9.7, 13.8, 12.7, 13.1,
       12.5,  8.5,  5. ,  6.3,  5.6,  7.2, 12.1,  8.3,  8.5,  5. , 11.9,
       27.9, 17.2, 27.5, 15. , 17.2, 17.9, 16.3,  7. ,  7.2,  7.5, 10.4,
        8.8,  8.4, 16.7, 14.2, 20.8, 13.4, 11.7,  8.3, 10.2, 10.9, 11. ,
        9.5, 14.5, 14.1, 16.1, 14.3, 11.7, 13.4,  9.6,  8.7,  8.4, 12.8,
       10.5, 17.1, 18.4, 15.4, 10.8, 11.8, 14.9, 12.6, 14.1, 13. , 13.4,
       15.2, 16.1, 17.8, 14.9, 14.1, 12.7, 13.5, 14.9, 20. , 16.4, 17.7,
       19.5, 20.2, 21.4, 19.9, 19. , 19.1, 19.1, 20.1, 19.9, 19.6, 23.2,
       29.8, 13.8, 13.3, 16.7, 12. , 14.6, 21.4, 23. , 23.7, 25. , 21.8,
       20.6, 21.2, 19.1, 20.6, 15.2,  7. ,  8.1, 13.6, 20.1, 21.8, 24.5,
       23.1, 19.7, 18.3, 21.2, 17.5, 16.8, 22.4, 20.6, 23.9, 22. , 11.9]), 'feature_names': array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7'), 'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000\n        - PTRATIO  pupil-teacher ratio by town\n        - B        1000(Bk - 0.63)^2 where Bk is the proportion of black people by town\n        - LSTAT    % lower status of the population\n        - MEDV     Median value of owner-occupied homes in $1000's\n\n    :Missing Attribute Values: None\n\n    :Creator: Harrison, D. and Rubinfeld, D.L.\n\nThis is a copy of UCI ML housing dataset.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/housing/\n\n\nThis dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.\n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\n\nThe Boston house-price data has been used in many machine learning papers that address regression\nproblems.   \n     \n.. topic:: References\n\n   - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.\n   - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.\n", 'filename': 'boston_house_prices.csv', 'data_module': 'sklearn.datasets.data'}

C:\Users\hp\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
    :func:`~sklearn.datasets.fetch_california_housing`) and the Ames housing
    dataset. You can load the datasets as follows::

        from sklearn.datasets import fetch_california_housing
        housing = fetch_california_housing()

    for the California housing dataset and::

        from sklearn.datasets import fetch_openml
        housing = fetch_openml(name="house_prices", as_frame=True)

    for the Ames housing dataset.

  warnings.warn(msg, category=FutureWarning)

## Analysing the Data

In [3]:
data = boston.data
target = boston.target
print(data)
print(target)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 30.3 34.6 34.9 32.9 24.1 42.3 48.5 50.  22.6 24.4 22.5 24.4 20.
 21.7 19.3 22.4 28.1 23.7 25.  23.3 28.7 21.5 23.  26.7 21.7 27.5 30.1
 44.8 50.  37.6 31.6 46.7 31.5 24.3 31.7 41.7 48.3 29.  24.  25.1 31.5
 23.7 23.3 22.  20.1 22.2 23.7 17.6 18.5 24.3 20.5 24.5 26.2 24.4 24.8
 29.6 42.8 21.9 20.9 44.  50.  36.  30.1 33.8 43.1 48.8 31.  36.5 22.8
 30.7 50.  43.5 20.7 21.1 25.2 24.4 35.2 32.4 32.  33.2 33.1 29.1 35.1
 45.4 35.4 46.  50.  32.2 22.  20.1 23.2 22.3 24.8 28.5 37.3 27.9 23.9
 21.7 28.6 27.1 20.3 22.5 29.  24.8 22.  26.4 33.1 36.1 28.4 33.4 28.2
 22.8 20.3 16.1 22.1 19.4 21.6 23.8 16.2 17.8 19.8 23.1 21.  23.8 23.1
 20.4 18.5 25.  24.6 23.  22.2 19.3 22.6 19.8 17.1 19.4 22.2 20.7 21.1
 19.5 18.5 20.6 19.  18.7 32.7 16.5 23.9 31.2 17.5 17.2 23.1 24.5 26.6
 22.9 24.1 18.6 30.1 18.2 20.6 17.8 21.7 22.7 22.6 25.  19.9 20.8 16.8
 21.9 27.5 21.9 23.1 50.  50.  50.  50.  50.  13.8 13.8 15.  13.9 13.3
 13.1 10.2 10.4 10.9 11.3 12.3  8.8  7.2 10.5  7.4 10.2 11.5 15.1 23.2
  9.7 13.8 12.7 13.1 12.5  8.5  5.   6.3  5.6  7.2 12.1  8.3  8.5  5.
 11.9 27.9 17.2 27.5 15.  17.2 17.9 16.3  7.   7.2  7.5 10.4  8.8  8.4
 16.7 14.2 20.8 13.4 11.7  8.3 10.2 10.9 11.   9.5 14.5 14.1 16.1 14.3
 11.7 13.4  9.6  8.7  8.4 12.8 10.5 17.1 18.4 15.4 10.8 11.8 14.9 12.6
 14.1 13.  13.4 15.2 16.1 17.8 14.9 14.1 12.7 13.5 14.9 20.  16.4 17.7
 19.5 20.2 21.4 19.9 19.  19.1 19.1 20.1 19.9 19.6 23.2 29.8 13.8 13.3
 16.7 12.  14.6 21.4 23.  23.7 25.  21.8 20.6 21.2 19.1 20.6 15.2  7.
  8.1 13.6 20.1 21.8 24.5 23.1 19.7 18.3 21.2 17.5 16.8 22.4 20.6 23.9
 22.  11.9]

## Converting Data to DataFrame

In [4]:
import pandas as pd
boston_dataframe = pd.DataFrame(data)
boston_dataframe

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

## Adding Heading to DataFrame

In [5]:
boston_dataframe.columns = boston.feature_names
temp = None
temp_dataframe = pd.DataFrame(temp)
check = []
for i in boston_dataframe:
    name = i + '_' + i
    check = check + [name]
    boston_dataframe[i + '_' + i] = boston_dataframe[i] ** 2
    
for i in boston_dataframe:
    check = check + [i]
    for j in boston_dataframe:
        if j in check:
            continue
        else:
            temp_dataframe[i + '_' + j] = boston_dataframe[i]*boston_dataframe[j]
temp_dataframe

,CRIM_ZN,CRIM_INDUS,CRIM_CHAS,CRIM_NOX,CRIM_RM,CRIM_AGE,CRIM_DIS,CRIM_RAD,CRIM_TAX,CRIM_PTRATIO,...,RAD_TAX,RAD_PTRATIO,RAD_B,RAD_LSTAT,TAX_PTRATIO,TAX_B,TAX_LSTAT,PTRATIO_B,PTRATIO_LSTAT,B_LSTAT
0,0.11376,0.014599,0.0,0.003400,0.041554,0.412064,0.025849,0.00632,1.87072,0.096696,...,296.0,15.3,396.90,4.98,4528.8,117482.40,1474.08,6072.570,76.194,1976.5620
1,0.00000,0.193082,0.0,0.012808,0.175358,2.154759,0.135652,0.05462,6.60902,0.486118,...,484.0,35.6,793.80,18.28,4307.6,96049.80,2211.88,7064.820,162.692,3627.6660
2,0.00000,0.192940,0.0,0.012799,0.196079,1.667419,0.135552,0.05458,6.60418,0.485762,...,484.0,35.6,785.66,8.06,4307.6,95064.86,975.26,6992.374,71.734,1583.1049
3,0.00000,0.070567,0.0,0.014825,0.226525,1.482546,0.196233,0.09711,7.18614,0.605319,...,666.0,56.1,1183.89,8.82,4151.4,87607.86,652.68,7379.581,54.978,1160.2122
4,0.00000,0.150529,0.0,0.031625,0.493500,3.742510,0.418595,0.20715,15.32910,1.291235,...,666.0,56.1,1190.70,15.99,4151.4,88111.80,1183.26,7422.030,99.671,2115.4770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.00000,0.747176,0.0,0.035887,0.412920,4.327733,0.155235,0.06263,17.09799,1.315230,...,273.0,21.0,391.99,9.67,5733.0,107013.27,2639.91,8231.790,203.070,3790.5433
502,0.00000,0.540071,0.0,0.025940,0.277052,3.472209,0.103555,0.04527,12.35871,0.950670,...,273.0,21.0,396.90,9.08,5733.0,108353.70,2478.84,8334.900,190.680,3603.8520
503,0.00000,0.724867,0.0,0.034815,0.423862,5.529160,0.131697,0.06076,16.58748,1.275960,...,273.0,21.0,396.90,5.64,5733.0,108353.70,1539.72,8334.900,118.440,2238.5160
504,0.00000,1.307409,0.0,0.062795,0.744554,9.786387,0.261800,0.10959,29.91807,2.301390,...,273.0,21.0,393.45,6.48,5733.0,107411.85,1769.04,8262.450,136.080,2549.5560
505,0.00000,0.565601,0.0,0.027166,0.285882,3.830728,0.118762,0.04741,12.94293,0.995610,...,273.0,21.0,396.90,7.88,5733.0,108353.70,2151.24,8334.900,165.480,3127.5720

## Combining two Data Frames

In [6]:
boston_dataframe

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,...,CHAS_CHAS,NOX_NOX,RM_RM,AGE_AGE,DIS_DIS,RAD_RAD,TAX_TAX,PTRATIO_PTRATIO,B_B,LSTAT_LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,...,0.0,0.289444,43.230625,4251.04,16.728100,1.0,87616.0,234.09,157529.6100,24.8004
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,...,0.0,0.219961,41.229241,6225.21,24.672082,4.0,58564.0,316.84,157529.6100,83.5396
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,...,0.0,0.219961,51.624225,3733.21,24.672082,4.0,58564.0,316.84,154315.4089,16.2409
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,...,0.0,0.209764,48.972004,2097.64,36.750269,9.0,49284.0,349.69,155732.8369,8.6436
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,...,0.0,0.209764,51.079609,2937.64,36.750269,9.0,49284.0,349.69,157529.6100,28.4089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,...,0.0,0.328329,43.467649,4774.81,6.143458,1.0,74529.0,441.00,153656.1601,93.5089
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,...,0.0,0.328329,37.454400,5882.89,5.232656,1.0,74529.0,441.00,157529.6100,82.4464
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,...,0.0,0.328329,48.664576,8281.00,4.698056,1.0,74529.0,441.00,157529.6100,31.8096
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,...,0.0,0.328329,46.158436,7974.49,5.706843,1.0,74529.0,441.00,154802.9025,41.9904
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,...,0.0,0.328329,36.360900,6528.64,6.275025,1.0,74529.0,441.00,157529.6100,62.0944

In [7]:
for i in temp_dataframe:
    boston_dataframe[i] = temp_dataframe[i]

In [8]:
boston_dataframe

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,...,RAD_TAX,RAD_PTRATIO,RAD_B,RAD_LSTAT,TAX_PTRATIO,TAX_B,TAX_LSTAT,PTRATIO_B,PTRATIO_LSTAT,B_LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,...,296.0,15.3,396.90,4.98,4528.8,117482.40,1474.08,6072.570,76.194,1976.5620
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,...,484.0,35.6,793.80,18.28,4307.6,96049.80,2211.88,7064.820,162.692,3627.6660
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,...,484.0,35.6,785.66,8.06,4307.6,95064.86,975.26,6992.374,71.734,1583.1049
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,...,666.0,56.1,1183.89,8.82,4151.4,87607.86,652.68,7379.581,54.978,1160.2122
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,...,666.0,56.1,1190.70,15.99,4151.4,88111.80,1183.26,7422.030,99.671,2115.4770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,...,273.0,21.0,391.99,9.67,5733.0,107013.27,2639.91,8231.790,203.070,3790.5433
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,...,273.0,21.0,396.90,9.08,5733.0,108353.70,2478.84,8334.900,190.680,3603.8520
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,...,273.0,21.0,396.90,5.64,5733.0,108353.70,1539.72,8334.900,118.440,2238.5160
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,...,273.0,21.0,393.45,6.48,5733.0,107411.85,1769.04,8262.450,136.080,2549.5560
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,...,273.0,21.0,396.90,7.88,5733.0,108353.70,2151.24,8334.900,165.480,3127.5720

In [9]:
X2 = boston_dataframe.values
print(X2)
boston_dataframe.describe()

[[6.3200000e-03 1.8000000e+01 2.3100000e+00 ... 6.0725700e+03
  7.6194000e+01 1.9765620e+03]
 [2.7310000e-02 0.0000000e+00 7.0700000e+00 ... 7.0648200e+03
  1.6269200e+02 3.6276660e+03]
 [2.7290000e-02 0.0000000e+00 7.0700000e+00 ... 6.9923740e+03
  7.1734000e+01 1.5831049e+03]
 ...
 [6.0760000e-02 0.0000000e+00 1.1930000e+01 ... 8.3349000e+03
  1.1844000e+02 2.2385160e+03]
 [1.0959000e-01 0.0000000e+00 1.1930000e+01 ... 8.2624500e+03
  1.3608000e+02 2.5495560e+03]
 [4.7410000e-02 0.0000000e+00 1.1930000e+01 ... 8.3349000e+03
  1.6548000e+02 3.1275720e+03]]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,...,RAD_TAX,RAD_PTRATIO,RAD_B,RAD_LSTAT,TAX_PTRATIO,TAX_B,TAX_LSTAT,PTRATIO_B,PTRATIO_LSTAT,B_LSTAT
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,...,506.000000,506.000000,506.00000,506.000000,506.000000,506.00000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,...,5231.539526,184.982806,3053.44749,151.154644,7702.055336,138823.11502,5818.871146,6547.619334,239.290334,4274.823238
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,...,6418.517581,180.171923,2960.05577,196.562582,3732.003358,64619.91997,5083.126041,1837.557901,145.807763,2613.501822
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,...,198.000000,13.600000,7.68000,3.160000,2692.800000,213.12000,498.960000,6.464000,25.431000,5.580800
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,...,1136.500000,73.500000,1483.70250,30.050000,4913.600000,101240.04000,2051.340000,6140.250000,122.942000,2355.214275
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,...,1790.000000,84.800000,1933.35000,57.630000,5924.100000,119658.91500,3724.380000,7078.025500,205.030000,3804.722600
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,...,15984.000000,484.800000,2778.30000,171.480000,13453.200000,160982.30250,8489.782500,7695.286500,334.360500,5640.628650
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,...,15984.000000,484.800000,9525.60000,911.280000,14291.100000,282195.90000,25288.020000,8421.600000,766.994000,15070.293000

## Spliting the Data to Train and Test

In [10]:
from sklearn import model_selection
X_train,X_test,Y_train,Y_test = model_selection.train_test_split(data,target,random_state = 0)
X2_train,X2_test,Y2_train,Y2_test = model_selection.train_test_split(X2,target,random_state = 0)

## Import LinearRegression for Training Algorithm

In [11]:
from sklearn.linear_model import LinearRegression
alg1 = LinearRegression()
alg2 = LinearRegression()

## Fit the Data in Algorithm

In [12]:
alg1.fit(X_train,Y_train)
alg2.fit(X2_train,Y2_train)

LinearRegression()

## Predict the Output

In [13]:
X_pred = alg1.predict(X_train)
Y_pred = alg1.predict(X_test)
X2_pred = alg2.predict(X2_train)
Y2_pred = alg2.predict(X2_test)
X_pred,Y_pred,X2_pred,Y2_pred

(array([13.54334096, 21.03611757, 35.25707372, 19.31180705, 12.9193462 ,
        13.83454251, 22.66868871, 14.2409856 , 31.24023391, 25.2746277 ,
        15.13346462, 24.27169368,  9.08842615, 14.82179159, 21.01155502,
        32.97485525, 27.96169238, 25.76241079, 15.56154982, 31.08187689,
        28.10293564, 13.79628381,  7.39293584, 28.48119204, 25.40996121,
         4.34170732, 28.48040075, 17.16788093, 29.49717483, 20.3114614 ,
        15.95499192, 17.81088079, 12.68905582,  8.44914207, 19.28629969,
        34.45678405, 32.9718556 , 23.57990095, 19.63359906, 22.95623269,
        26.85871334, 21.77624643, 16.93785832, 32.00415847, 10.62790654,
        19.32739398, 32.23307479, 18.75153571, 15.81064522, 18.67130015,
        14.4104764 , 24.58123176, 24.07953473, 16.49458446, 13.19945057,
        20.38069625, 24.75377888, 17.22571167, 24.97600846, 22.55118033,
        27.83912426, 35.9434255 , 16.45240418, 11.58522008, 34.68756396,
        31.00776222, 20.65966773, 39.55056576, 29.0078266 , 29.00999968,
        17.31262092, 26.97466269, 40.01865097, 28.7187013 , 16.66413461,
        37.34643087, 35.15447445, 13.07044909, 28.80715127, 21.38482965,
        24.40626805, 21.33531517, 23.31155929, 27.87734985, 29.64995287,
        13.96911009, 25.85695736, 23.25131305, 12.5172144 , 13.69132664,
        25.49785082, 19.23696262, 30.60970957, 10.68212969, 23.48533064,
        17.03772708, 16.59934046, 22.33849495, 21.64394065, 11.71895973,
        25.15637916, 28.67840378, 20.25954038, 12.29601933, 25.48647773,
        25.97788959, 25.15821406, 23.51129012, 26.3731198 , 16.49102756,
        21.75968781, 36.02321867, 20.85067436, 36.07873626, 25.56983603,
        21.44247854, 15.84506236, 31.18713035, 20.99511987, 27.92647342,
        14.60379914, 32.07992935, 13.94845716,  1.23511893, 19.25466741,
        14.00196732, 37.65403649, 15.67829929, 14.41406636, 27.20645037,
        23.2464109 , 18.24857906, 30.51887451, 27.50134148, 27.13968907,
        24.60935817, 24.32980985, 23.81791552, 10.93621298, 20.86529541,
        13.35873342, 17.0560766 , 12.47216364, 28.19611065, 14.9205006 ,
        16.00534023, 28.57141456, 14.52365083, 21.4528413 , 12.63065565,
        13.83861061, 22.68360321, 21.32323132, 14.71936262, 20.93062808,
        16.9384149 , 24.66277466, 12.38856379, 34.71025176, 12.09307942,
        43.12440696, 31.30392303, 35.09706888, 21.48351767, 15.75285005,
        26.49228094, 29.46272822, 14.04142297, 26.51551881, 36.8554903 ,
        17.46375116, 10.44046135, 34.34341413, 35.79823559, 18.20672279,
        22.53409628, 17.86688629, 24.41834416, 19.68127577, 27.1348803 ,
        -4.7935806 , 20.6011946 , 35.54607447, 36.43371743, 25.13606463,
        27.46241836, 20.65069471, 20.84329828, 15.58318868, 20.47268487,
        20.86062578, 27.84177682, 19.73629934,  7.12516955, 16.38246922,
        32.44651078, 35.11864523, 17.36525685, 18.65663525, 23.67343616,
         6.80990982, 21.34024409, 23.94671395, 16.30258603, 18.52875495,
        21.88776238, 27.36090769, 25.54237562, 37.08784116, 15.2242206 ,
        28.77849376, 25.52619072, 22.17904272, 38.63798003, 20.66824195,
        23.40207582, 22.82493385, 12.56743905, 20.2029527 , 33.69463297,
        24.57218076, 17.87538397, 33.6633018 , 21.5370783 , 28.49979067,
        32.39305372, 36.59624894, 21.81981625, 24.01793038, 22.52428337,
        31.65872288, 22.46304999, 18.63305293, 21.83697296, 28.4661344 ,
        22.58740941, 21.62999687, 16.79524835, 17.34557435, 16.83301518,
        17.28066864, 16.28550867, 31.64269524, 23.70579496, 17.45022197,
        19.82025367, 33.62355545, 13.91668199, 25.10891516, 17.25562451,
        30.46090593, 29.71427389, 22.40525244, 20.65051631, 35.3314866 ,
        22.68182948, 33.12430511, 20.90706516, 31.44634261, 30.91564395,
        37.494095  , 26.70059511, 21.69588344, 28.83832617, 16.00988216,
        26.60997592, 21.08145518, 30.60264526,  9.55495526, 30.76710928,
         5.53663323, 15.44974971, 18.02894191, 35.4348492 , 32.08398124,
        10.69820228, 12.96384144, 21.79517021, 34.61455395, 18.57831239,
        19.19735358, 14.75516101, 26.01658627, 41.09013514, 25.22455914,
        41.98596333, 25.03305836, 22.20260718, 11.99313537, 11.89639019,
        13.84579354, 18.33211266,  2.76281682, 27.58675347, 26.19392263,
        41.02318491, 21.04333396, 21.1439921 , 34.25776492, 33.14993993,
         9.40811041, 24.88140767, 43.38286578, 16.8379618 , 17.76543177,
        25.67192935, 18.48178432,  5.83291142, 19.12535018, 35.14965525,
        16.00174108, 23.24384522, 13.37064218, 24.4543297 , 18.64700522,
        17.20586437, 18.78318498, 33.29462253, 19.51402668, 30.79124528,
        32.81042416, 41.18865165, 18.86227874, 16.28627585, 37.50271065,
        17.99877336,  9.38800263, 15.12505568, 25.00719566, 19.50708006,
        16.44689479, 27.20334758, 12.65574828,  5.6347011 , 18.92984523,
         9.48845791, 27.88422139,  4.1390608 , 29.17459175, 32.35105717,
        22.39880532, 16.61914886, 17.82249438, 20.90744416, 33.22275733,
        27.7475763 , 19.46707152, 20.57924537,  6.52093646, 28.78143245,
        24.77659687, 22.3556873 , 13.62498123, 25.39982217, 19.4377186 ,
         8.51235752, 26.67675444, 16.00772031, 31.51716876, 32.62095138,
        25.42099968, 18.40637845, 30.66934392, 21.42806664, 25.45254246,
        26.01337051, 31.77172624, 24.27505504, 34.62093852, 16.95175246,
        19.25167734, 18.49249415, 40.95624463, 25.23248739, 19.47226601,
        33.23059648, 23.70761701, 18.22343193, 23.11159723]),
 array([24.95233283, 23.61699724, 29.20588553, 11.96070515, 21.33362042,
        19.46954895, 20.42228421, 21.52044058, 18.98954101, 19.950983  ,
         4.92468244, 16.09694058, 16.93599574,  5.33508402, 39.84434398,
        32.33549843, 22.32772572, 36.54017819, 31.03300611, 23.32172503,
        24.92086498, 24.26106474, 20.71504422, 30.45072552, 22.45009234,
         9.87470006, 17.70324412, 17.974775  , 35.69932012, 20.7940972 ,
        18.10554174, 17.68317865, 19.71354713, 23.79693873, 29.06528958,
        19.23738284, 10.97815878, 24.56199978, 17.32913052, 15.20340817,
        26.09337458, 20.87706795, 22.26187518, 15.32582693, 22.85847963,
        25.08887173, 19.74138819, 22.70744911,  9.66708558, 24.46175926,
        20.72654169, 17.52545047, 24.45596997, 30.10668865, 13.31250981,
        21.52052342, 20.65642932, 15.34285652, 13.7741129 , 22.07429287,
        17.53293957, 21.60707766, 32.91050188, 31.32796114, 17.64346364,
        32.69909854, 18.56579207, 19.32110821, 18.81256692, 23.04351442,
        22.81649956, 23.99800754, 30.62733254, 28.8662207 , 25.78198145,
         5.00689605, 36.83409088, 23.80490328, 27.36965299, 19.33057146,
        28.51439846, 19.19147448, 18.81694283, 37.94245021, 39.3441055 ,
        23.90759744, 24.95985846, 15.70262358, 25.92060968, 16.56968829,
        15.76303806, 12.89190083, 24.4389405 , 30.9319885 , 22.36798609,
        20.17628607,  0.22819711, 25.26459847, 15.35369364, 17.7983399 ,
        25.44689554, 22.46612234, 32.57911019, 22.01436262, 27.37542798,
        23.31348039,  6.29811532, 14.75925592, 22.44945223, 29.11172812,
        32.97160856, 12.85457141, 19.79963356, 20.60017439, 12.06928939,
        23.38532482,  4.75243811, 19.8342911 ,  9.17555571, 44.63299931,
        30.63144603, 12.29971299, 17.53804831, 21.50222331, 23.63281301,
        20.28259817, 35.17973368]),
 array([17.0920011 , 16.68012794, 32.28431441, 15.30414674,  7.90129708,
        12.95816217, 19.38995855,  8.35972033, 34.400316  , 21.92921103,
        13.21410249, 27.94943319,  7.02511688,  9.58862708, 24.03409748,
        37.70445704, 26.99371436, 26.08239664, 15.70274556, 33.79320043,
        32.6481271 , 10.7276867 ,  8.30254965, 26.11467875, 26.53400449,
        14.61850576, 27.16907307, 17.81340944, 26.37050967, 20.08746188,
        15.46842762, 17.23317403, 13.61999804,  6.80817166, 18.06538674,
        34.54512064, 33.18228991, 32.00207426, 22.14832855, 21.87994199,
        25.63098606, 24.00574692, 15.13321192, 28.49108199, 13.11862761,
        18.96947532, 30.71921503, 19.45382016, 10.69592072, 18.69814084,
        17.37456769, 25.13476908, 20.915002  , 16.4417526 ,  9.43376044,
        19.84000767, 22.30271323, 18.28777217, 26.75255846, 24.38864561,
        26.50931214, 45.90335797, 15.16995481,  8.14222426, 32.74275144,
        31.11285242, 17.30761325, 46.70997366, 22.29445074, 25.33114145,
        18.38370071, 24.02634059, 44.17942352, 24.52096667, 14.74425503,
        38.20874842, 34.75923581, 16.78271948, 27.29973149, 24.88538757,
        25.34479055, 23.077247  , 20.19817314, 28.02534186, 27.92875215,
        10.73752465, 20.28830364, 18.41958227,  9.96352465, 15.19126393,
        25.61160111, 17.50544585, 32.6155447 , 14.91353536, 21.10468787,
        17.17543534, 15.08936209, 19.64134819, 20.23344493, 14.59710314,
        20.53884698, 25.78323534, 19.20946931, 13.71974347, 21.8946429 ,
        24.90357414, 31.2373815 , 20.52875374, 24.1620971 , 12.40245096,
        21.36405253, 34.34811728, 15.52045952, 23.2636702 , 24.26668889,
        22.54435602, 15.45499758, 31.85412141, 25.74892597, 29.92342698,
        14.70711327, 33.58632991, 13.09071409, 15.15199043, 12.64800919,
        14.42622411, 43.10918089, 17.00679146, 14.17582644, 29.34923702,
        21.50189442, 16.64916157, 33.59640101, 25.23260858, 24.32599839,
        22.00322086, 22.55702876, 23.13640497,  8.83865524, 18.91932676,
        31.37734885, 17.89726919, 13.57799113, 27.05983232, 15.44897544,
        15.75479876, 30.53076139, 12.82428682, 21.13341215, 11.39443978,
        13.78243898, 20.79589636, 20.26819032, 18.57868476, 22.02576067,
        20.78340815, 23.17249795, 10.93641805, 34.23640271, 25.44522835,
        51.26823097, 27.03415576, 31.85823718, 19.43398224, 15.29396327,
        23.56728735, 26.17452196, 15.9093987 , 21.76708806, 46.96475591,
        20.08973484, 11.17996398, 35.41093933, 34.74489891, 17.52667077,
        19.84692243, 16.49211984, 22.65427461, 19.89204074, 21.94071748,
         9.60887015, 18.86452661, 43.12311559, 45.84449938, 23.57944267,
        23.28425943, 20.61020406, 24.94018497, 17.65361388, 13.21299257,
        21.30464368, 24.16278486, 17.89901176, 14.7984933 , 16.19060429,
        32.53460035, 34.39713786, 21.428435  , 17.41531898, 21.72310791,
         2.05895286, 22.53222542, 18.1078672 , 16.10565029, 18.31153999,
        19.66807953, 27.48343394, 23.16737395, 39.2054579 , 14.81418113,
        32.77516505, 30.73299062, 23.38537376, 44.66253669, 19.51618181,
        20.98125476, 24.34871987, 11.90862112, 20.28343731, 33.44888761,
        20.12876605, 15.14383175, 36.91433775, 16.48594209, 29.81863729,
        31.46122304, 34.95740295, 19.13460082, 18.10296996, 23.52966345,
        29.82707518, 22.33010422, 19.54811776, 18.3630764 , 31.63185062,
        20.8508137 , 19.96213155, 19.16258875, 12.44514812, 11.55345592,
        16.20387601, 16.13823052, 29.58935826, 21.46344562, 11.61576154,
        20.09730908, 31.87438962, 13.79838309, 24.12136824, 14.51858449,
        24.71782846, 21.73724494, 40.88855221, 20.61059396, 41.86424165,
        26.99357645, 33.8898302 , 22.00033852, 30.48935391, 46.18038624,
        40.23038878, 21.15509101, 23.06811954, 28.66175725, 17.11946243,
        25.28144483, 18.77335952, 28.30515052, 17.67303979, 30.89573161,
        10.85633471, 14.00871905, 17.26512731, 35.29691009, 31.36184471,
        15.42871413, 15.55211977, 23.74572361, 39.52603302, 18.78571842,
        21.02162132, 13.33794218, 21.62061127, 48.03101186, 25.64703328,
        48.2096817 , 25.58997939, 22.16713403, 15.81419084,  8.76305408,
        16.65072454, 16.76641958, 10.07007949, 25.61999303, 25.61630089,
        51.33178756, 19.65732258, 25.75369848, 35.73096225, 30.70708187,
         9.61581418, 24.63838951, 53.55344992, 11.22132423, 16.1874526 ,
        22.95479438, 18.56829124,  9.61190623, 19.21482377, 34.59810648,
        13.99921106, 23.68492997, 13.61453371, 20.31114138, 15.40198884,
        12.35589218, 18.27986875, 31.17941227, 17.24961435, 32.6879185 ,
        49.53593393, 48.98437852, 18.03648126, 16.99402079, 42.69750987,
        14.7526398 , 16.72776419, 15.04257425, 27.14756816, 16.86328141,
        13.28369433, 23.10251348, 11.67059581,  5.53205583, 19.24161094,
        13.70364804, 23.98880488,  7.01715208, 27.16729515, 32.29374433,
        21.87229978, 13.92196092, 15.11455247, 21.17306181, 30.53897983,
        24.70885023, 21.01256141, 16.8911353 ,  7.50335208, 22.04711016,
        20.84944379, 23.77686972, 14.92026377, 23.62547236, 19.68013977,
         8.03755429, 24.90253131, 21.18013298, 28.65153658, 33.01153442,
        22.02895451, 14.53401958, 27.20901029, 21.4995339 , 24.89138205,
        25.41128598, 27.66300473, 22.23770939, 31.64833471, 18.50805987,
        19.16659494, 19.4616463 , 50.08437485, 24.45066545, 18.44617723,
        34.59522039, 19.49691071, 18.27070643, 20.70427474]),
 array([ 23.65294081,  26.7375643 ,  29.61078315,  10.15490293,
         19.63821608,  19.69567722,  22.04569772,  20.8219241 ,
         11.62647856,  17.55251923,   6.02831471,  13.30819476,
         14.08746399,   8.24933315,  48.92086715,  35.54459237,
         23.67706411,  37.23811936,  32.28994966,  22.44461026,
         25.04445792,  21.34495855,  20.89993569,  27.34950626,
         18.20884762,  30.05914961,  16.38882367,  18.27410131,
         34.58728224,  13.84776749,  16.56901813,  18.20821168,
         20.00399253,  19.68630353,  26.44755882,  16.35902867,
          7.10012009,  36.71844063,  16.76163017,  13.4975915 ,
         22.14796642,  19.86834244,  19.74483032,  19.04895022,
         11.823238  ,  22.30991276,  17.9596158 ,   9.9207432 ,
         12.34654968,  23.09629767, -26.05316354,  25.18108608,
         20.72351713,  52.44146808,   5.7506184 ,  21.16062991,
         16.67681922,  17.94789708,  17.07672773,  19.79482459,
         23.94848059,  21.07920154,  33.14839064,  29.17411146,
         19.31538063,  30.77385559,  15.19001363,  19.27968125,
         14.28902591,  21.0217457 ,  18.17979319,  21.77419932,
         27.27988436,  29.59118561,  28.01422907,   9.30237051,
         41.98096211,  23.57185114,  26.31853086,  19.07604318,
         26.31654757,  18.68443745,  21.82845944,  41.76250816,
         44.124338  ,  24.75612697,  23.00111462,  12.36563547,
         32.97750424,  15.883512  ,  18.83795677,   9.18828122,
         21.12990826,  29.96045984,  17.69264721,  21.70124105,
         13.25650224,  24.96092522,  13.6714964 ,  15.60548478,
         25.38906926,  19.15962141,  30.84958417,  19.3180996 ,
         27.06140523,  19.93887424,   7.83712161,  20.29586097,
         18.22177943,  25.73460894,  36.21513111,  13.7796668 ,
         16.79165488,  19.17926261,  15.27289768,  19.34749235,
          6.24016005,  20.50524461,  11.22369929,  51.59743425,
         28.7954706 ,  11.24042043,  17.25143184,  21.4161027 ,
         19.72865917,  19.28660345,  36.92350037]))

## Comparing Scores

In [14]:
def cod_score(Y_Test, Y_Pred):
    u = ((Y_Test - Y_Pred)**2).sum()
    v = ((Y_Test - Y_Test.mean())**2).sum()
    result = 1 - (u/v)
    return result
train_score = cod_score(Y_train,X_pred)
test_score = cod_score(Y_test,Y_pred)
print("Train: ",train_score)
print("Test: ",test_score)

train_score_2 = cod_score(Y2_train,X2_pred)
test_score_2 = cod_score(Y2_test,Y2_pred)
print("Train_2: ",train_score_2)
print("Test_2: ",test_score_2)

Train:  0.7697699488741149
Test:  0.6354638433202129
Train_2:  0.9520519609032727
Test_2:  0.6074721959808899